name: DEPLOY

on:
  pull_request:
    branches: [main]

jobs:
  BUILD:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚
        uses: actions/checkout@v2

      - name: 🛂
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: 🚢
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: 👷
        id: docker_build
        run: sh docker/build.sh

      - name: 🚀
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: sh update-tree-api.sh

      - name: 🔀
        uses: BaharaJr/merge-pr@0.0.1
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
